org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

minecraft_version=1.21-rc1
yarn_mappings=1.21-pre2+build.1
loader_version=0.15.11

mod_version=1.1.1

fabric_version=0.100.0+1.21
rei_version=16.0.729
architectury_version=13.0.1
// EMI-1.21: https://github.com/emilyploszaj/emi/pull/558
//  Very unstable but it works as a dev target. 
//  Remember to set "use-batched-renderer: false;" (otherwise it might crash)
emi_version=1.1.6-SNAPSHOT+1.21-pre1+fabric
cloth_basic_math_version=0.6.1
cloth_config_version=15.0.127
