org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

minecraft_version=1.20.2
yarn_mappings=1.20.2+build.4
loader_version=0.16.14

mod_version=1.2.2-beta.5+1.20.2

fabric_version=0.91.6+1.20.2
rei_version=13.1.773
architectury_version=10.1.20
emi_version=1.1.22+1.20.2
cloth_config_version=12.0.137
jei_version=16.0.0.2
